# These are supported funding model platforms
buy_me_a_coffee: pablowilliams # Replace with your username
## Apoie este projeto ☕  

Se quiser contribuir, você pode me apoiar no [Buy Me a Coffee](https://www.buymeacoffee.com/pablowilliam) ou via PIX:  

**PIX:** contato@site.multichannel.pt
